"""
Misclassification analysis utility for the arch-recognition experiments.

This script uses the prediction CSV generated by the model scripts and creates:
- a CSV containing only misclassified test samples
- separate False Positive and False Negative CSV files
- a compact summary JSON

For the final ResNet50 baseline reported in the study, the expected test-set
confusion matrix is:
    [[560, 59],
     [ 61,816]]
with class order [No Arch, Has Arch].

Therefore:
- False Positives = 59
- False Negatives = 61
- Total errors = 120

The script does not infer qualitative failure categories automatically.
The qualitative categories reported in the manuscript were obtained through
manual visual inspection of all 120 ResNet50 misclassified images.
"""

import argparse
import json
from pathlib import Path

import pandas as pd
from sklearn.metrics import confusion_matrix


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--predictions-csv",
        required=True,
        help=(
            "Prediction CSV generated by a model script. "
            "Must contain true_label and predicted_label."
        ),
    )
    parser.add_argument(
        "--output-dir",
        default="outputs/failure_analysis",
    )
    parser.add_argument(
        "--verify-resnet50-final",
        action="store_true",
        help=(
            "Verify that the supplied predictions reproduce the final "
            "ResNet50 baseline test results reported in the study."
        ),
    )
    args = parser.parse_args()

    df = pd.read_csv(args.predictions_csv)

    required = {"true_label", "predicted_label"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(
            f"Missing required columns in prediction CSV: {sorted(missing)}"
        )

    # The fixed test set contains exactly 1,496 samples.
    if len(df) != 1496:
        raise ValueError(
            f"Expected 1,496 test samples, but found {len(df)}."
        )

    true_label = df["true_label"].astype(int)
    pred_label = df["predicted_label"].astype(int)

    cm = confusion_matrix(
        true_label,
        pred_label,
        labels=[0, 1],
    )

    tn, fp, fn, tp = cm.ravel()

    misclassified = df[true_label != pred_label].copy()
    false_positives = df[
        (true_label == 0) & (pred_label == 1)
    ].copy()
    false_negatives = df[
        (true_label == 1) & (pred_label == 0)
    ].copy()

    summary = {
        "class_order": ["No Arch", "Has Arch"],
        "test_samples": int(len(df)),
        "true_negatives": int(tn),
        "false_positives": int(fp),
        "false_negatives": int(fn),
        "true_positives": int(tp),
        "total_misclassifications": int(len(misclassified)),
    }

    if args.verify_resnet50_final:
        expected_cm = [[560, 59], [61, 816]]
        if cm.tolist() != expected_cm:
            raise AssertionError(
                "Predictions do not match the final ResNet50 baseline "
                f"confusion matrix. Found {cm.tolist()}, "
                f"expected {expected_cm}."
            )

        if len(misclassified) != 120:
            raise AssertionError(
                f"Expected 120 errors, found {len(misclassified)}."
            )

        summary["resnet50_final_verification"] = "passed"

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    misclassified.to_csv(
        output_dir / "misclassified_test_images.csv",
        index=False,
    )
    false_positives.to_csv(
        output_dir / "false_positives.csv",
        index=False,
    )
    false_negatives.to_csv(
        output_dir / "false_negatives.csv",
        index=False,
    )

    with open(
        output_dir / "failure_analysis_summary.json",
        "w",
        encoding="utf-8",
    ) as f:
        json.dump(summary, f, indent=2)

    print("\nMISCLASSIFICATION SUMMARY")
    print("-------------------------")
    print(f"Test samples           : {len(df)}")
    print(f"True Negatives (TN)    : {tn}")
    print(f"False Positives (FP)   : {fp}")
    print(f"False Negatives (FN)   : {fn}")
    print(f"True Positives (TP)    : {tp}")
    print(f"Total errors           : {len(misclassified)}")

    if args.verify_resnet50_final:
        print("Final ResNet50 check   : PASSED")


if __name__ == "__main__":
    main()
